version: '3.8'

services:
  device1:
    stdin_open: true
    tty: true
    entrypoint: >
      /bin/bash -c "
        tc qdisc add dev eth0 root netem delay 50ms 20ms distribution normal loss 2% corrupt 1% reorder 10% 25% &&
        tcpdump -i eth0 -w /app/device1.pcap &
        python3 /app/main.py
      "
    cap_add:
    - NET_ADMIN
    build: .
    container_name: device1
    volumes:
      - ./:/app
    networks:
      testnet:
        ipv4_address: 172.20.0.2

  device2:
    stdin_open: true
    tty: true
    entrypoint: >
      /bin/bash -c "
        tcpdump -i eth0 -w /app/device2.pcap &
        python3 /app/main.py
      "
    build: .
    container_name: device2
    volumes:
      - ./:/app
    networks:
      testnet:
        ipv4_address: 172.20.0.3

  device3:
    stdin_open: true
    tty: true
    build: .
    container_name: device3
    volumes:
      - ./:/app
    networks:
      testnet:
        ipv4_address: 172.20.0.4

networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
